#+title: Architectural Patterns
#+author: Edmilson Monteiro Rodrigues Neto

* Business Logic x Architectural Patterns

Business logic is the most important part of software. However, it is not the only part of a software system.

Architectural patterns introduce organizational principles for the different aspects of a codebase and present
clear boundaries between them: /How the business logic is wired to the system's input, output, and other
infrastructural components./

Choosing the appropriate way to organize the codebase, or the correct architectural pattern, is crucial to support
implementation of the business logic in the short term and alleviate maintenance.

* Layered Architecture

Layered architecture is one of the most common architectural patterns.

It organizes teh codebase into horizontal layers, with each layer addressing one of the following technical
concerns;
+ Interaction with the consumers
+ Implementing Business Logic
+ Persisting the data

In its classic form, it has three layers:
+ Presentation Layer (PL) (View)
+ Business Logic Layer (BLL) (Controller)
+ Data Access Layer (DAL) (Model)

** Presentation Layer

The presentation layer implements the program's user interface for interactions with its consumers.

This can be any means for trigerring the program's behavior, both synchronous and asynchronous.

+ GUI
+ CLI
+ API
+ Subscriptions to ingoing events
+ Publishing outgoing events

In summary, the presentation layer is the program's public interface.

** Business Logic Layer

As the name suggests, this layer is responsible for implementing and encapsulating the program's business
logic. /The heart of the software/.

** Data Access Layer

The data access layer provides access to persistence mechanisms.

This can be multiple databases, object storages, message buses, etc.

This is also used for integration with external APIs, cloud services, etc.

** Communication between layers

The layers are integrated in a top-down communication model:
Each layer can hold a dependency only on the layer directly beneath it.

This enforces decoupling of implementatino concerns and reduces the knowledge shared between the layers.

** Variation
It's common to see the layered architecture pattern extended with an additional layer: The service layer

*** Service Layer

This is an intermediary layer between the program's presentation and the business logic layers.

The service layer acts as a facade for the business logic layer.

It exposes an interface that corresponds with the public interface's methods, encapsulating the required
orchestration of the underlying layers.

Having an explicit service level has a number of advantages:

+ We can reuse the same service layer to serve multiple public interfaces, for example, a graphical user
  interface and an API.
+ It improves modularity by gathering all related methods in one place.
+ It further decouples the presentation and business logic layers.
+ It makes it easier to test the business functionality.

  
**** Terminology

+ Presentation Layer = User Interface Layer
+ Service Layer = Application Layer
+ Business Logic Layer = Domain Layer = Model Layer
+ Data Access Layer = Infrastructure Layer

** When to use layered architecture

The dependency between the business logic and the data access layers makes this architectural pattern a good fit for
a system with its business logic implemented using the transaction scrip or active record pattern.

However, the pattern makes it challenging to implement a domain model, as the business entities should have no
dependency and no knowledge of the underlying infrastructure.

The layered architecture's top-down dependency makes it a lot harder to implement a domain model.

*** Optional: Layers Versus Tiers

The layers architecture is often confused with the N-Tier architeture.

Despite the similarities between the two patterns, layers and tiers are conceptually different: A layer is a logic
boundary, whereas a tier is a physical boundary.

All layers in the layered architecture are bound by the same lifecycle: They are implemented, evolved, and deployed as
one single unit.

On the other hand, a tier is an independently deployable service.

* Ports & Adapters

** Terminology
Essentially, both the presentation layer and data access layer represent integration with external components:
+ Databases
+ External Services
+ User Interface Frameworks


These technical implementation details do not reflect the system's business logic, so, they all go into the infrastructure
layer.

** Dependency Inversion Principle

The dependency inversion principle states that high-level modules, which implement the business logic, should not depend on
low-level modules.

Instead, with the DIP, the infrastructure layer depends on the business logic layer.

So, the Infrastructure Layer depends on the Application Layer, that depends on the Business Logic Layer.

** Integration of Infrastructural Components

The core goal of the ports & adapters architecture is to decouple the system's business logic from its infrastructural
components.

Instead of referencing and calling the infrastructural components directly, the business lofic layer defines "ports" that have
to be implemented by the infrastructure layer.

The infrastructure layer implements "adapters": concrete implementations of the ports' interfces for working with different
technologies.

** Variants

The ports & adapters architecture is also known as hexagonal architecture, onion architecture and clean architecture.

*I Disagree from this part of the book*

** When to use ports & adapters

The decoupling of the business logic from all technological concerns makes this architecture a perfect fit for business logic
implemented with the domain model pattern.

* Command-Query Responsibility Segregation

The CQRS pattern is based on the same organizational principles for business logic and infrastructural concerns as ports & adapters.

However, this pattern enables presentation of the system's data in multiple persistent models.

** Polyglot Modeling

In many cases, it may be difficult, if not impossible, to use a single model of the system's business domain to address all of the
system's need.

For example, OnLine Transaction Processing (OLTP) and OnLine Analytical Processing (OLAP) may require different represetnations of the
system's data.

** Implementation

As the name suggests, the pattern segregates the responsibilities of the system's models.

There are two types of models:
+ The Command Execution Model
+ The Read Models

*** Command Execution Model

CQRS devotes a single model to executing operations that modify the system's state (system commands). This model is used to implement the
business logic, validate rules and enforce invariants.

This is also the only model representing strongly consistent data: The system's source of truth.

It should be possible to read the strongly consistent state of a business entity and have optimistic concurrency support when updating it.

*** Read Models (projections)

The system can define as many models as needed to present data to users or supply information to other systems.

A read model is a precached projection. It can reside in a durable database, flat file, or in-memory cache.

Proper implementation of CQRS allows for wiping out all data of a projection and regenerating it from scratch.

This also enables extending the system with additional projections in teh future - Models that couldn't have been foreseen originally.

Finally, read models are read-only. None of the system's operations can directly modify the read models' data.

** Projecting Read Models

For the read models to work, the system has to project changes from teh command execution to all its read models.

The projection of read models is similar to the notion of a materialized view in relational databases:
Whenever source tables are updated, the changes have to be reflected in the precached views.

Next, let's see two ways to generate projections: synchronously and asynchronously.

*** Synchronous Projections

Synchronous projections fetch changes to the OLTP data through the catch-up subscription model.

+ The projection engine queries the OLTP database for added or updated records after the last processed checkpoint.
+ The projection engine uses the updated data to regenerate/update the system's read model.
+ The projection enfine stores the checkpoint of the last processed record. This value will be used during the next
  iteration for getting records added or modified after the last processed record.

For the catch-up subscription to work, the command execution model has to checkpoint all the appended or updated
database records.

The synchronous projection method makes it trivial to add new projections and regenerate existing ones from scratch, by
just resetting the checkpoint to 0. 

*** Asynchronous Projections

In the asynchronous projection scenario, the command execution model publishes all committed changes to a message bus.

The system's projection engines can subscribe to the published messages and use them to update the read models.

** Challanges

Despite the apparent scaling and performance advantages of the asynchronous projection method, it is more prone to the
challanges of distributed computing.

If the messages are processed out of order or duplicated, inconsistent data will be projected into the read models.

For these reasons, it's advisable to always implement synchronous projection, and, optionally, an additional asynchronous
projection on top of it.

** Model Segregation

In the CQRS architecture, the responsibilities of the system's models are segregated according to their type.

A command can only operate on the strongly consistent command execution model.

A query cannot directly modify any of the system's persisted state, neither the read models nor the command execution model.

Although a query cannot modify data, a command can return data without any problem.

A command should always let the caller know whether it has succeeded or failed.

+ If it has failed, why did it fail?
+ Was there a validation or technical issue?

The caller has to know how to fix the command.

Therefore, a command can, and, in many cases should return data.

The only limitarion here is that the returned data should originate from teh Command Execution Model, as we cannot expect that
the projections will be refreshed immediately.

** When to Use CQRS

This  pattern can be useful for applications that need to work with the same data in multiple models, potentially stored in different
kinds of database.

It is a great fit for event-sourced domain models also.

* Scope

These architectures should not be used system wide, nor even restrained to the bounded context, but, instead, restrained by their
subdomains.
