#+title: Event Storming
#+author: Edmilson Monteiro Rodrigues Neto

* What is EventStorming?

EventStorming is a low-tech activity for a group of people to brainstorm and rapidly model
a business process. In a sense, EventStorming is a tactical tool for sharing business domain
knowledge.

An EventStorming session has a /scope/: The business process that the group is interested in
exploring. The participants are exploring the process as a series of domain events, over a
timeline. Step by step, the model is enhanced with additional concepts.

* Who Should Pariticipate in EventStorming?

Ideally, anyone related to the business domain in question can participate:
+ Engineers
+ Domain experts
+ Product Owners
+ Testers
+ UI/UX Designers
+ Support
+ Etc.

But, take care to not grow the group too big. Try at most 10 participants.

* What do you need for EventStorming?

+ Modeling Space: Something such as a wall, or a white board, as big as possible.
+ Sticky Notes: A lot of sticky notes of different colors. These will represent
  different concepts of the business domain.
+ Markers: Markers to write on the sticky notes. (At least 1 for each participant)
+ Snacks: A typical session lasts about two to four hours, so snacks are nice.
+ Room: A spacious room, without things such as tables, that will prevent the users
  to move freely and observe all the modeling space. Also, no chairs.


* The EventStorming Process

This process has usually 10 steps, during each step, the model is enriched with additional
information and concepts.

** Step 1: Unstructured Exploration

We start with a brainstorm of the domain events related to the business domain being explored.
A /domain event/ is anything interesting that has happened in the business. (Past tense)

During this step, all participants are grabbing a bunch of *orange* stickers, writing down
whatever it comes to mind, and sticking in the modeling space, without worry about ordering,
redundancy, etc.

Examples: Order initialized, Request declined, Order Shipped, Notification Sent, etc.

** Step 2: Timelines

Next, the participants go over the generated domain events and organize them in the order in which
they occur in the business domain.

The events should start with the "happy path scenario".

Once the "happy path" is done, alternative scenarios can be added. The flow branching can be expressed
using arrows drawn on the modelling surface.

This step is also the time to fix incorrect events, remove duplicates, and, of coutse, add missing events
if necessary.

** Step 3: Pain Points

Once you have the events organized in a timeline, use this broad view to identify points in the process
that require attention. These can be bottlenecks, manual steps that require automation, missing documentations,
or missing domain knowledge.

It's important to make these inefficiencies explicit so that it will be easy to return to them as the
EventStorming session progresses, or to address them afterwards.

*The Pain Points are marked with diamond (rotated) pink sticky notes*

** Step 4: Pivotal Events

Once you have a timeline of events augmented with pain points, look for signigicant business events
indicating a change in context or phase. These are called /pivotal events/ and are marked with a
*vertical bar dividing the events before and after the pivotal event*, with the pivotal event in the
middle of the bar.

Pivotal events are an indicator of potential bounded context boundaries.

** Step 5: Commands

Whereas a domain event describes something that has already happened, a /command/ describes what triggered
the event or flow of events. Commands describe the system's operations and, contraty to domain events, are
formulated in the imperative, such as:
+ Publish Campaign
+ Roll back transaction
+ Submit Order

  
*Commands are written on light blue sticky notes*, and placed on the modeling space before the events they can
produce. If a particular command is executed by an actor in a specific role, *the actor information is added to*
*the command on a small yellow sticker*. The actor represents a user persona within the business domain, such as:
+ Customer
+ Administrator
+ Editor

Naturally, not all commands will have an associated actor. Only add it where it is obvious.

** Step 6: Policies

Almost always, some commands are added to the model, but have no specific actor associated with them. During this
step, we look for automation policies that might execute those commands.

An /automation policy/ is a scenario in which an event triggers the execution of a command. 

On the modeling surface, *policies are represented as purple stickers* connecting events to commands, with the name
"Policy" on it.

Such as we have a domain event (orange sticker) "Shipment approved", and a command (blue sticker) "Ship order".
If the command Ship Order occurs when the Shipment is approved, we put a purple sticker with "Policy" connecting
both the stickers.

If the command in question should be triggered only if some decision criteria is met, you can specify the decision
criteria explicitly on the policy sticky note.

For example, if you need to trigger the /escalate/ command, after the "complaint received" event, but only if the
complaint was received from a VIP customer, you can explicitly state the "Only for VIP Customers" condition on the
policy sticker.

If the events and commands are far apart, you can draw an arrow on the modelling surface to connect them.

** Step 7: Read Models

A read model is the view of data within the domain that the actor uses to make a decision to execute a command.
This one can be something such as:
+ A System Screen
+ A report
+ A notification
+ etc.


*The read models are represented by green sticky notes* with a short description of the source of information
needed to support the actor's decision. Since a command is executed after the actor has viewd the read model, on
the modeling surface, the read models are positioned before the commands.

Example:
The "Shopping Cart" Read Model, by the Actor "Customer", can start the Command "Submit Order", with the Domain Events:
+ Order Initialized
+ Shipping Cost Calculated
+ Order Shipped


** Step 8: External Systems

This step is about augmenting the model with external systems. An /external system/ is defined as any system that is not
a part of the domain being explored. It can execute commands (input) or can be notified about events (output).

*The external systems are represented by pinik sticky notes*.

For example:
An External System "CRM" can call the command "Ship Order"
As well, the Domain Event "Shipment approval", via a Policy, can communicate the event to the External System "CRM".

By the end of this step, all commands should either be executed by actors, triggered by policies, or called by external
systems.

** Step 9: Aggregates

Once all the events and commands are represented, the participants can start thinking about organizing related concepts
in aggregates. An /aggregate/ receives commands and produce events.

*Aggregates are represented as large yellow stickers, with commands on the left, and events on the right.*

** Step 10: Bounded Contexts

The last step of an EventStorming session is to look for aggregates that are related to each other, either because they
represent closely related functionality or because they're coupled through policies.

The groups of aggregates form natural candidates for bounded contexts' boundaries.

*The bounded contexts are represented with drawn boundaries*

* Variants

The creator of the EventStorming Alberto Brandolini, defines it as /guidance, not hard rules/.

One strategy is to start just with the steps 1-4, and continue the rest in following sessions.

But, most important than the EventStorming board, is the sharing of knowledge and generation of the ubiquitous language
generated by the EventStorming sessions.

The final board can be used to design, the most complex modelling: An Event Source Domain Model (though it is not necessary,
it gives you the knowledge to do it if required).

* When to use EventStorming

+ *Build a ubiquitous language*: As the group cooperates in building the model of the business process, they will synchronize
  the terminology and start using the same language.
+ *Model the business process*: It builds a model of the business process, that will discover the boundaries of aggregates and
  bounded contexts.
+ *Explore new business requirements*: It helps everyone to be on the same page, regarding the new functionality and reveal edge
  cases not covered by the business requirements.
+ *Recover Domain Knowledge*: Over time, domain knowledge can get lost. EventStorming is an effective way to merge the knowledge
  held by each participant into a single coherent picture.
+ *Explore ways to improve an existing business process*: Havind an end-to-end view of a business process provides the perspective
  needed to notice inefficiencies and opportunities to improve the process.
+ *Onboard new team members*: Facilitating an EventStorming session together with new members can expand their domain knowledge.

EventStorming will not be successful when the business process is simple or obvious, for example.
  
* Facilitation Tips
 
When introducing the EventStorming, it is nice to start with a small overview of what we are about to do, and to build a legend as we
go through the elements.

** Watch the Dynamics

As the workshop progresses, keep track of the energy of the group. If the dynamics are slowing down, maybe asking questions can reignite,
or maybe it's time to advance to the next step.

Everyone should participate in the modeling and the discussion. Involve the ones that are shying away.

The session is an intense activity, and, at some point, we will need a break. Wait for everyone to be back, and make a short summary of
where we are before continuing.


** Remote EventStorming

EventStorming was invented as a low-tech activity in which people interact and learn together in the same room.

However, some events, such as the COVID-19 pandemic, and full remote companies, can make the need of an online meeting.

In addition, usually remote EventStorming session are more efficient with a smaller group, such as 5 participants.

