 #+title: The AWK Language
 #+author: Edmilson Monteiro Rodrigues Neto

 The last chapter was the tutorial

 Here we will go through examples and the specification of the language, deepening inside of it.

 Use the file ./snippets/countries for the examples

** Program Format

All AWK programs must be a series of pattern-action statements

Like this:

#+BEGIN_SRC awk
  /abacate/ { print $3 }
#+END_SRC

A statement can not have the pattern.

In this case, it's action is executed for all lines:

#+BEGIN_SRC awk
  { print $3 }
#+END_SRC

A statement can also not have an action.

In this case, it prints the whole line for each line that matches the pattern.

#+BEGIN_SRC awk
  /abacate/
#+END_SRC

* Patterns

We have six types of patterns in awk:

1. BEGIN { statements } == The statements are executed before the first input is read
2. END { statements } == The statements are executed after the last input is read
3. expression { statements } == The statements are executed at each input where expression is true (nonzero or nonnull)
4. / /regular expression/ / { statements } == The statements are executed at each input line that contains a string matched by the regex
5. compound pattern { statements } == This is a pattern with logical operators. It is just like an expression but with logical operators
6. pattern1, pattern2 { statements } == Range pattern: Executes for each line between the one that matches pattern 1 and the one that matches pattern 2
   
** BEGIN and END

These cannot be combined.
They do not read input lines.

It's a way to control initialization and wrap up of the program.

Multiple BEGIN or END are executed in appearance order

One common use of BEGIN is to change the FS variable (Field Separator)

#+BEGIN_SRC awk
  BEGIN {
      FS = "\t"
      printf("%10s %6s %5s   %s\n\n",
             "COUNTRY", "AREA", "POP", "CONTINENT")
  }
  {
      printf("%10s %6d %5d   %s\n", $1, $2, $3, $4)
      area = area + $2
      pop = pop + $3
  }
  END { printf("\n%10s %6d %5d\n", "TOTAL", area, pop) }
#+END_SRC

** Expressions as Patterns

Any expression can be used as an operand of any operator.

If an expression has a numeric value but an operator requires a string value, the numeric value
is automatically into a string; similarly a string is converted into a number when an operator
demands a numeric value.

Any expression can be used as a pattern. If an expression used as a pattern has a nonzero or
nonnull value, at the current input line, then the pattern matches that line.

The typical expression patterns are those involving comparisons between numbers of strings.

A comparison expression contain one of the 6 relational operators, or one of the two string
matching operators.

+ <  : Less than
+ <= : Less than or Equal to
+ == : Equal to
+ != : Not equal to
+ >= : Greater than or equal to
+ >  : Greater than
+ ~  : matched by
+ !~ : not matched by

In a relational comparison if both operands are numeric, a numeric comparison is made;
otherwise, both are converted to string, and they compare strings.

If the expression is a comparison the line is executed if it returns true

If the expression is a mathematical expression it returns true for any non zero character.

String comparisons are made in character set order (Like ASCII).

** String Matching Patterns

Regular expressions apply here.

There are 3 types of string matching pattern:

1. /regexpr/ == Matched when the current input line contains a substring matched by regexp.
2. expression ~ /regexpr/ == Matches if the string value of expression contains a substring
   matched by regexpr
3. expression !~ /regexpr/ == Matches if the string value of expression does not contain a
   substring matched by regexpr

So, obviously, the first pattern is equal to $0 ~ /regexprs/

*** Regular Expressions

A regular expression is a notation for specifying and matching strings. Like an arithmetic
expression, a regexpr is a basic expression or one created by applying operators to component
expression.

The regular expression metacharacters are:

+ \  == This is the quote metachar. It can be used to quote metacharacters, or to matches a special simble, such as \t
+ ^  == Matches the beginning of a string
+ $  == Matches the end of a string
+ .  == Matches any single character
+ [] == Makes a character class, such as [ABC0] and matches any one of these 4 characters. These can be abbreviated, like [a-z].
  If it starts with ^, like [^0-9] matches any character except for digits, for example
+ |  == These operators combine regular expressions into larger ones: alternation A|B matches A or B
+ () == Matches the same strings as what its contents usually would
+ *  == Closure: A* matches zero or more A's
+ +  == Positive Closure: A+ matches one or more A's
+ ?  == Zero or One: A? matches the null string or A

Inside a character class, any character except for \, ^ at the beginning and - between two characters, mean their literal value.

So, [.] means a dot, and ^[^^] means any string that does not start with a ^.

Parentheses are used in regular expressions to specify how components are grouped.

We have also special quotes, that mean characters not writable:

+ \b   == backspace
+ \f   == formfeed
+ \n   == Newline
+ \r   == Carriage Return
+ \t   == tab
+ \ddd == octal values, where ddd is 1 to 3 digits between 0 and 7
+ \c   == any other character c literally, e.g.: \\ for backslash \" for ", etc.

ddd = /[0-7]{1,3}/


** Compound Patterns

A compund pattern is an expression that combines other patterns using parenthesis and the logical operators ||, && or !

** Range

pat1, pat2

This pattern matches each line between an occurrence of pat1 and the next occurrence of pat2 inclusive:

Some special variables:
+ FNR == The number of the line just read from the current input file
+ FILENAME == Name of the file being read.

* Actions

In a pattern action statement, the pattern determines when the action is to be executed. Sometimes an action is very simple,
other times it may be a sequence of several statements.

The statements in actions can include:
+ Expressions, with constants, variables, assignments, function calls, etc.
+ print expression-list
+ printf(format, expression-list)
+ if (expression) statement
+ if (expression) statement else statement
+ while (expression) statement
+ for (expression; expression; expression) statement
+ for (variable in array) statement
+ do statement while (expression)
+ break
+ continue
+ next
+ exit
+ exit expressions

** Expressions

Expresions are the simplest statements. They are building blocks of bigger statements.

Here are the most common types of expressions.

*** Constants
In AWK, constants is how Literals are called. They can be strings, such as "hello, world", or numeric such as 1e4

*** Variables

In awk, variables are all named pointers to values. They are numeric or strings depending on the operation they are participating
into.

If the variable is a string, but it is in a numeric operation, it will be converted to number, and vice versa.

**** Built-in Variables

Variables that all commands have.

| Variable | Meaning                                    | Default |
| ARGC     | number of command-line arguments           | -       |
| ARGV     | array of command-line arguments            | -       |
| FILENAME | name of current input file                 | -       |
| FNR      | Record Number in Current File              | -       |
| FS       | Field separator                            | " "     |
| NF       | Number of fields in Row                    | -       |
| NR       | Record Number                              | -       |
| OFMT     | Output Format for numbers                  | "%.6g"  |
| OFS      | Output Field Separator                     | " "     |
| ORS      | Output Record Separator                    | "\n"    |
| RLENGTH  | Length of string matched by match function | -       |
| RS       | Record Separator                           | "\n"    |
| RSTART   | Start of string matched by match function  | -       |
| SUBSEP   | Subscript Separator                        | "\034"  |

**** Field Variables

The fields of the current input line are called $1, $2... $NF. $0 refers to the whole line. They can be reassigned.

*** Arithmetic Operators

The usual: +, -, *, /, %, and ^. % is the module, and ^ is potency.

*** Comparison Operators

Used to compare both sides and return 1 if true, and 0 if false.

<=, <, ==, >, >=, !=, ~, !~

*** Logical Operators

Used to combine expresssions. Any expression can be in any side. The expression is considered falsy if it is 0 or a null
string, and truthy otherwise.

+ ||
+ &&
+ !

*** Conditional Expressions

These are the ternery operator: expr1 ? expr2 : expr3

*** Assignment Operators

These are the operators that assign a value to a variable.

Enhanced assignment is more performatic than simple assignment. Use it when you can:


+ =
+ +=
+ -=
+ %=
+ /=
+ *=
+ ^=

Increment and decrement operators are even more performatic, and they can be pre and post
operations:

+ n++
+ ++n
+ n--
+ --n

*** Built in Arithmetic Functions

| Function   | ValueReturned                                     |
| atan2(y,x) | actangent of y/x in the range -pi to pi           |
| cos(x)     | cosine of x, in radians                           |
| exp(x)     | exponential function of x. e^x                    |
| int(x)     | integer part of x. Truncated towards 0 when x > 0 |
| log(x)     | natural (base e) logarithm of x                   |
| rand()     | random number r, where 0 <= r < 1                 |
| sin(x)     | sine of x, with x in radians                      |
| sqrt(x)    | square root of x                                  |
| srand(x)   | x is new seed for rand()                          |

Useful contants can be computed with these functions:
+ atan2(0, -1) gives pi.
+ exp(1) gives e.
+ to compute base-y logarithm of x, use log(x)/log(y)

Calling srand(x) sets the starting point of the generator from x.

rand is a pseudo-random floating point number between 0 and 1.

Calling srand() sets the starting point from the time of day.

The assignment: randint = int(n * rand()) + 1 sets randint to a random integer between 1 and n inclusive.

The assignment: x = int(x + 0.5) rounds the value x to the nearest integer when x is positive.

*** String Operators

The only string operation is concatenation, and it has no explicit operator. They are created by writing
constants, variables, fields, array elements, function values, and other expressions next to one another.

For example: { print NR ": " $0 } prints the file with the number of the lines.

*** Strings as Regular Expressions

While so far we have only seen regexprs, enclosed by brackets as the right operands of ~, any expression
can be used there. For example:

#+BEGIN_SRC awk
  BEGIN { digits = "^[0-9]+$" }
  $2 ~ digits
#+END_SRC

Will print all lines in which the second field is a string of digits.

Since expressions can be concatenated, a regular expression can be built up from components.

The following program echoes input lines that are valid floating point numbers:

#+BEGIN_SRC awk
  BEGIN {
      sign = "[+-]?"
      decimal = "[0-9]+[.]?[0-9*]"
      fraction = "[.][0-9]+"
      exponent = "([eE]" sign "[0-9]+)?"
      number = "^" sign "(" decimal "|" fraction ")" exponent "$"
  }
  $0 ~ number
#+END_SRC

In a matching expression, a quoted string like "^[0-9]+$" can normally be used interchangeably
with a regexpr enclosed in slashes, such as =/^[0-9]+$/=.

There is one exception, however. If the string in quotes is to match a literal occurence of a
regexpr metacharacter, the backslash must be quoted. So, these two expressions are equivalent:

#+BEGIN_SRC awk
  $0 ~ /(\+|-)[0-9]+/
  $0 ~ "(\\+|-)[0-9]+"
#+END_SRC

*** Built-In String Functions

In this table: r => regexpr, either in // or in ""; s, t => strings; n, p => integers.

| Functions               | Description                                                                                             |
| gsub(r,s)               | Substitute s for r globally in $0, return number of substitutions made                                  |
| gsub(r,s,t)             | Substitute s for r globally in string t, return number of substitutions made                            |
| index(s,t)              | Return first position of string t in s, or 0 if t is not present                                        |
| length(s)               | Return number of characters in s                                                                        |
| match(s,r)              | Test whether s contains a substring matcherd by r. Return index or 0, sets RSTART and RLENGTH           |
| split(s,a)              | Split s into array a on FS, return number of fields                                                     |
| split(s,a,fs)           | Split s into array a on field separator fs                                                              |
| sprintf(fmt,expre-list) | Return expr-list formatted according to format string fmt                                               |
| sub(r,s)                | Substitute s for the leftmost longest substring of $0 matched by r, return number of substitutions made |
| sub(r,s,t)              | Substitute s for the leftmost longest substring of t matched by r, return number of substitutions made  |
| substr(s,p)             | Return suffix of s starting at position p                                                               |
| substr(s,p,n)           | Return substring of s of length n starting at position p                                                |

gsub => global sub

sub => s///

gsub => s///g

*** Control-Flow Statements

+ { statements }
  statement grouping
+ if (expression) statement
  if expression is truthy execute statement
+ if (expression) statement1 else statement2
  if expression is truthy execute statement1, else execute statement2
+ while (expression) statement
  If expression is true, execute statement, then repeat
+ for (expression1; expression2; expression3) statement
  runs expression1, then loops while expression2 is truthy, and execute expression3
  at the end of the statements
+ for (variable in array) statement
  execute statement with variable set to each subscript in array in turn
+ do statement while (expression)
  execute statement; if expression is true, repeat
+ break
  immediately leave innermost enclosing while, for or do
+ continue
  start next iteration of innermost enclosing while, for or do
+ next
  start next iteration of main input loop (Fetches next input line.)
+ exit
  exit expression
  Go immediately to the END action. If within the END action, exit the program entirely.
  Return expression as program status.

*** Empty Statement

This can be described by a line with just a ;

For example:
#+BEGIN_SRC awk
  BEGIN { FS = "\t" }
  {
      for (i = 1; 0 <= NF && $i != ""; i++)
          ;
      if (i <= NF)
          print
  }
#+END_SRC

This program prints all lines with an empty field.

*** Arrays

Awk provides one-dimensional arrays for storing strings and numbers.

Arrays and array elements need not be declared, nor is there any need to specify how many
elements an array has.

Like variables, array elements spring into existence by being mentioned: at birth, they have
0 or "" as value.

Actually, is easy, though maybe slow, to read the entire input in an  array.

For example, a simple tac command:

#+BEGIN_SRC awk
  {x[NR] = $0}
  END {
      for (i = NR; i > 0; i--) print x[i]
  }
#+END_SRC

In awk arrays are /associative arrays/

Some operations in arrays:

+ subscript in array:
  Returns 1 if subscript already exists in array, 0 if not.

  "asia" in continents

+ delete statement
  An array element may be deleted with:
  
  delete array[subscript]

+ The split function
  This function might create an array from a string, based on a field separator:

  split("7/4/76", arr, "/")

  They will be stored in numbered indexes starting on 1

+ Multidimensional Arrays
  Awk does not provide multidimensional arrays, but it does emulate it, as string concatenation is
  automatic in array keys.

  So arr[1,2] = 5 means the key "1,2" leads to the value 5

  Arrays elements cannot be arrays.

* User Defined Functions

A function can be defined with:

function name(parameters-list) {
    statements
}

The body of a function may contain a return statement

return expression

expression is optional.

return is also optonal.

If the last statement executed is not a return, the return is undefined.

Example function:

#+BEGIN_SRC awk
  function max(m, n) {
      return m > n ? m : n
  }
#+END_SRC

Functions in awk work with values, not references, except with arrays.

If a parameter is not provided, it is startup with a null value.

If a function works with a variable not inside the function parameter list, it is a global variable.

* Output

The print and printf statements generate output.

** Output Statements

+ print
  print $0 on standard output
+ print expression, expression, ...
  print expressions separated by OFS, terminated by ORS
+ print expression, expression, ... > filename
  print on file filename instead of standard output
+ print expression, expression, ... >> filename
  append to file filename instead of overwriting previous contents
+ print expression, expression, ... | command
  print to standard input of command
+ printf ...
  The same ones as print, but with formatting
+ close(filename), close(command)
  break connection between print and filename or command
+ system(command)
  execute command, value is status return of command

The argument list of a printf statement does not need to be enclosed in parentheses, except if they have
relational operators.

** Print Statement

print prints the expressions passed.

If none is passed it prints $0

It separates the expressions by OFS

It ends on ORS

** Output Separators

Output separators are OFS for field separators and ORS for record separators.

** The printf Statement.

It is exactly equal to print statement, but it is like if the string printed passed through sprintf through the
parameters passed.

*** Printf Format Control Characters

| Character | Print Expression As                                                           |
| c         | ASCII character                                                               |
| d         | decimal integer                                                               |
| e         | [-]d.dddddE[+-]dd                                                             |
| f         | [-]ddd.ddddd                                                                  |
| g         | e or f conversion, whichever is shorter, with nonsignificant zeros suppressed |
| o         | unsigned octal number                                                         |
| s         | string                                                                        |
| x         | unsigned hexadecimal number                                                   |
| %         | %% prints a %                                                                 |

*** Examples of Printf Specifications

| fmt       |      $1 | printf(fmt, $1) |
| %c        |      97 | a               |
| %d        |    97.5 | 97              |
| %5d       |    97.5 | "   97"         |
| %e        |    97.5 | 9.750000e+01    |
| %f        |    97.5 | 97.500000       |
| %7.2f     |    87.5 | "  97.50"       |
| %g        |    97.5 | 97.5            |
| %.6g      |    97.5 | 97.5            |
| %o        |      97 | 141             |
| %06o      |      97 | 000141          |
| %x        |      97 | 61              |
| !%s!      | January | !January!       |
| !%10s!    | January | !   January!    |
| !%-10s!   | January | !January   !    |
| !%.3s!    | January | !Jan!           |
| !%10.3s!  | January | !       Jan!    |
| !%-10.3s! | January | !Jan       !    |
| %%        | January | %               |

** Output into Files

Be carefull.

print $1, $2 > $3 prints the $1 and $2 separated by OFS into $3, finishing in ORS

print $1, ($2 > $3) prints $1 and wether $2 is greater than $3

** Ouput into Pipes

It is also possible to direct output into a pipe instead of a file on systems that support pipes.

It will open a shell subprocess after it, like:

print message | "cat 1>&2" will redirect the message to a shell that will run cat 1>&2.

Normally, a file or pipe is created and opened only once during the run of a program.

If the pipe is explicitly closed, and then reused, it will be reopened.

** Closing Files and Pipes

The statement close(expr) closes a file or pipe denoted by expr. The string value of expr must be the
same as the string used to create the file or pipe in the first place.

close is necessary if you intend to write a file, then read it later in the same program.

* Input

There are several ways of providing input to an awk program.

The most common is asking for it to read one or more files:

awk 'program' file1 file2...

Or redirecting to it via pipes:

grep -E 'Asia' countries | awk 'program'

** Input Separators

They are FS for fields and RS for records.

If they have more than 1 character, they are taken as regular expressions

** The getline function

The function getline can be used to read input either from the current input or from a file or pipe

This function fetches the next input record and preforms the normal field-splitting operations, setting NF, NR and FNR.

The expression:

+ getline <"file"

  reads from file instead of the current input.

  It has no effect on NR or FNR, but NF is set.

The expression:

+ getline x <"file"

  gets the next record from file into x; no splitting is done.

  NF, NR and FNR are untouched

*** Getline Function

| Expression           | Sets            |
| getline              | $0, NF, NR, FNR |
| getline var          | var, NR; FNR    |
| getline <file        | $0, NF          |
| getline var <file    | var             |
| cmd pipe getline     | $0, NF          |
| cmd pipe getline var | var             |

As an example, this program copies its input to its output, except that each line like:

#include "filename"

is replaced by the contents of the file filename

#+BEGIN_SRC awk
  /^#include/ {
      gsub(/"/, "", $2)
      while (getline x <$2 > 0)
          print x
      next
  }
  { print }
#+END_SRC

It is also possible to pipe the result of a command into getline

** Command-Line variable Assignment

An awk program is usually like:

awk -f progfile f1 f2...
awk 'program' f1 f2...

In these command lines, f1, f2, etc. are command-line arguments that normally represent filenames.

If a filename has the form var=text, however, it is treated as an assignment of text to var, at
the time it would usually be read by a file, possibilitating changes in a variable value before
and after reading a file.

** Command-Line Arguments

ARGC and ARGV work exactly equal to C or any other language.

ARGV[0] is the program call

The other are the arguments, numbered, up to ARGC-1

* Interaction with Other Programs

** The system function
The function system(expression) calls a subprocess shell with the command passed

The same include program as before
#+BEGIN_SRC awk
  $1 == "#include" {
      gsub(/"/, "", $2)
      system("cat " $2)
      next
  }
  { print }
#+END_SRC

** Making a Shell Command from an AWK Program

Read the chapter, this is just explaining how to create shell scripts calling awk.
